image: java:8-jdk

stages:
  - test
  - build
  
services:
  - 'mysql:5.5'
  
variables:
  MYSQL_DATABASE: testempdb
  MYSQL_URL: jdbc:mysql://mysql/testempdb
  MYSQL_USER: app_root
  MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root
 
maven-test:
  image: maven:3.5.2-jdk-8
  stage: test
  script: "mvn test"
  
maven-build:
  image: maven:3.5.2-jdk-8
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar
  